apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-devsecops
  template:
    metadata:
      labels:
        app: pfe-devsecops
    spec:
      containers:
        - name: web
          image: pfe-devsecops:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
